export default {
  animations: [
    // key-value pairs, should be read as a Map
    [
      'small/walk',
      [
        'small/walk-0.png',
        'small/walk-1.png',
        'small/walk-2.png',
        'small/walk-3.png',
        'small/walk-4.png',
        'small/walk-5.png',
        'small/walk-6.png',
        'small/walk-7.png'
      ]
    ],
    [
        'small/gameover',
        [
            'small/gameover-0.png',
            'small/gameover-1.png'
        ]
    ],
    [
        'small/grow',
        [
            'small/grow-0.png',
            'small/grow-1.png',
            'small/grow-2.png',
            'small/grow-3.png',
            'small/grow-4.png',
            'small/grow-5.png',
            'small/grow-6.png'
        ]
    ],
    [
        'small/idle',
        [
            'small/idle-0.png',
            'small/idle-1.png'
        ]
    ],
    [
        'small/jump',
        [
            'small/jump-0.png'
        ]
    ],
    [
        'small/run',
        [
            'small/run-0.png',
            'small/run-1.png',
            'small/run-2.png',
            'small/run-3.png',
            'small/run-4.png',
            'small/run-5.png',
            'small/run-6.png',
            'small/run-7.png',
            'small/run-8.png',
            'small/run-9.png',
            'small/run-10.png',
            'small/run-11.png',
            'small/run-12.png',
            'small/run-13.png',
            'small/run-14.png',
            'small/run-15.png'
        ]
    ],
    [
        'small/stand',
        [
            'small/stand-0.png'
        ]
    ]
  ]
}
